Scraper Class
CorrelAidxNL/forward43 pull request #12
Opened 2021-04-26 07:06 UTC by akashrajkn

Created a `ForwardScraper` class with Spoofing.

- [ ] Kickstarter scraper subclass
- [ ] Ulule scraper subclass
- [ ] Start some good scraper subclass

2021-04-26 21:06 UTC, andrewsutjahjo requested changes
Nice one!
Good abstractions into classes, and good documentation. It just needs a bit of a cleanup of some unused code, maybe a logger instead of prints, and some error handling so nothing breaks from an errant spanner in the works.
A few simple unit tests would be good to ensure that anyone working on this code after you will know when they break it :)

2021-04-26 21:06 UTC, andrewsutjahjo commented on forward43/scraper_kickstarter.py
> +                response  = self.get_response(url)
This could use a bit of error handling, otherwise one timeout will break the whole pipeline

2021-04-28 13:31 UTC, andrewsutjahjo approved these changes
Nice one!

2021-04-28 21:34 UTC, akashrajkn commented
I will add unit tests in a separate PR.

2021-04-28 21:34 UTC, merged